/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COMMONAPI_Speed_Status_STUB_DEFAULT_HPP_
#define V1_COMMONAPI_Speed_Status_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v1/commonapi/SpeedStatusStub.hpp>
#include <cassert>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace commonapi {

/**
 * Provides a default implementation for SpeedStatusStubRemoteEvent and
 * SpeedStatusStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT SpeedStatusStubDefault
    : public virtual SpeedStatusStub {
public:
    COMMONAPI_EXPORT SpeedStatusStubDefault()
        : remoteEventHandler_(this),
          interfaceVersion_(SpeedStatus::getInterfaceVersion()) {
    }

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return interfaceVersion_;
    }

    COMMONAPI_EXPORT SpeedStatusStubRemoteEvent* initStubAdapter(const std::shared_ptr< SpeedStatusStubAdapter> &_adapter) {
        CommonAPI::Stub<SpeedStatusStubAdapter, SpeedStatusStubRemoteEvent>::stubAdapter_ = _adapter;
        return &remoteEventHandler_;
    }

    COMMONAPI_EXPORT virtual const int16_t &getSpeedAttribute() {
        return speedAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const int16_t &getSpeedAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getSpeedAttribute();
    }
    COMMONAPI_EXPORT virtual void setSpeedAttribute(int16_t _value) {
        const bool valueChanged = trySetSpeedAttribute(std::move(_value));
        if (valueChanged) {
            fireSpeedAttributeChanged(speedAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual void setSpeedAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, int16_t _value) {
        (void)_client;
        setSpeedAttribute(_value);
    }


protected:
    COMMONAPI_EXPORT virtual bool trySetSpeedAttribute(int16_t _value) {
        if (!validateSpeedAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<SpeedStatusStubAdapter> stubAdapter = CommonAPI::Stub<SpeedStatusStubAdapter, SpeedStatusStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockSpeedAttribute(true);
            valueChanged = (speedAttributeValue_ != _value);
            speedAttributeValue_ = std::move(_value);
            stubAdapter->lockSpeedAttribute(false);
        } else {
            valueChanged = (speedAttributeValue_ != _value);
            speedAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateSpeedAttributeRequestedValue(const int16_t &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual void onRemoteSpeedAttributeChanged() {
        // No operation in default
    }
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual SpeedStatusStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(SpeedStatusStubDefault *_defaultStub)
            : 
              defaultStub_(_defaultStub) {
        }

        COMMONAPI_EXPORT virtual void onRemoteSpeedAttributeChanged() {
            assert(defaultStub_ !=NULL);
            defaultStub_->onRemoteSpeedAttributeChanged();
        }

        COMMONAPI_EXPORT virtual bool onRemoteSetSpeedAttribute(int16_t _value) {
            assert(defaultStub_ !=NULL);
            return defaultStub_->trySetSpeedAttribute(std::move(_value));
        }

        COMMONAPI_EXPORT virtual bool onRemoteSetSpeedAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, int16_t _value) {
            (void)_client;
            return onRemoteSetSpeedAttribute(_value);
        }

    private:
        SpeedStatusStubDefault *defaultStub_;
    };
protected:
    SpeedStatusStubDefault::RemoteEventHandler remoteEventHandler_;

private:

    int16_t speedAttributeValue_ {};

    CommonAPI::Version interfaceVersion_;
};

} // namespace commonapi
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COMMONAPI_Speed_Status_STUB_DEFAULT
