/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/commonapi/TempStatusSomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createTempStatusSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< TempStatusSomeIPProxy>(_address, _connection);
}

void initializeTempStatusSomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:commonapi.TempStatus:v1_0:TempStatus",
        0x1238, 0x567c, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
        "commonapi.TempStatus:v1_0",
        &createTempStatusSomeIPProxy);
}

INITIALIZER(registerTempStatusSomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeTempStatusSomeIPProxy);
}

TempStatusSomeIPProxy::TempStatusSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection),
          temp_(*this, CommonAPI::SomeIP::eventgroup_id_t(0x812e), CommonAPI::SomeIP::event_id_t(0x812e), CommonAPI::SomeIP::method_id_t(0x1b58), true, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE, false, CommonAPI::SomeIP::method_id_t(0x1b59), true, static_cast< CommonAPI::SomeIP::IntegerDeployment<int16_t>* >(nullptr))
{
}

TempStatusSomeIPProxy::~TempStatusSomeIPProxy() {
    completed_.set_value();
}

TempStatusSomeIPProxy::TempAttribute& TempStatusSomeIPProxy::getTempAttribute() {
    return temp_;
}


void TempStatusSomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 1;
    ownVersionMinor = 0;
}

std::future<void> TempStatusSomeIPProxy::getCompletionFuture() {
    return completed_.get_future();
}

} // namespace commonapi
} // namespace v1
