/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COMMONAPI_Maneuver_PROXY_HPP_
#define V1_COMMONAPI_Maneuver_PROXY_HPP_

#include <v1/commonapi/ManeuverProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/AttributeExtension.hpp>
#include <CommonAPI/Factory.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {

template <typename ... _AttributeExtensions>
class ManeuverProxy
    : virtual public Maneuver,
      virtual public ManeuverProxyBase,
      virtual public _AttributeExtensions... {
public:
    ManeuverProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~ManeuverProxy();

    typedef Maneuver InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Returns the wrapper class that provides access to the attribute Steering.
     */
    virtual SteeringAttribute& getSteeringAttribute() {
        return delegate_->getSteeringAttribute();
    }
    /**
     * Returns the wrapper class that provides access to the attribute Throttle.
     */
    virtual ThrottleAttribute& getThrottleAttribute() {
        return delegate_->getThrottleAttribute();
    }



 private:
    std::shared_ptr< ManeuverProxyBase> delegate_;
};

typedef ManeuverProxy<> ManeuverProxyDefault;

namespace ManeuverExtensions {
    template <template <typename > class _ExtensionType>
    class SteeringAttributeExtension {
     public:
        typedef _ExtensionType< ManeuverProxyBase::SteeringAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< ManeuverProxyBase::SteeringAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        SteeringAttributeExtension(ManeuverProxyBase& proxy): attributeExtension_(proxy.getSteeringAttribute()) {
        }
    
        inline extension_type& getSteeringAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

    template <template <typename > class _ExtensionType>
    class ThrottleAttributeExtension {
     public:
        typedef _ExtensionType< ManeuverProxyBase::ThrottleAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< ManeuverProxyBase::ThrottleAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        ThrottleAttributeExtension(ManeuverProxyBase& proxy): attributeExtension_(proxy.getThrottleAttribute()) {
        }
    
        inline extension_type& getThrottleAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

} // namespace ManeuverExtensions

//
// ManeuverProxy Implementation
//
template <typename ... _AttributeExtensions>
ManeuverProxy<_AttributeExtensions...>::ManeuverProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< ManeuverProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< ManeuverProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
ManeuverProxy<_AttributeExtensions...>::~ManeuverProxy() {
}


template <typename ... _AttributeExtensions>
const CommonAPI::Address &ManeuverProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool ManeuverProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool ManeuverProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& ManeuverProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& ManeuverProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> ManeuverProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace commonapi
} // namespace v1

namespace CommonAPI {
template<template<typename > class _AttributeExtension>
struct DefaultAttributeProxyHelper< ::v1::commonapi::ManeuverProxy,
    _AttributeExtension> {
    typedef typename ::v1::commonapi::ManeuverProxy<
            ::v1::commonapi::ManeuverExtensions::SteeringAttributeExtension<_AttributeExtension>, 
            ::v1::commonapi::ManeuverExtensions::ThrottleAttributeExtension<_AttributeExtension>
    > class_t;
};
}


// Compatibility
namespace v1_0 = v1;

#endif // V1_COMMONAPI_Maneuver_PROXY_HPP_
