/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COMMONAPI_Brake_Status_STUB_DEFAULT_HPP_
#define V1_COMMONAPI_Brake_Status_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v1/commonapi/BrakeStatusStub.hpp>
#include <cassert>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace commonapi {

/**
 * Provides a default implementation for BrakeStatusStubRemoteEvent and
 * BrakeStatusStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT BrakeStatusStubDefault
    : public virtual BrakeStatusStub {
public:
    COMMONAPI_EXPORT BrakeStatusStubDefault()
        : remoteEventHandler_(this),
          interfaceVersion_(BrakeStatus::getInterfaceVersion()) {
    }

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return interfaceVersion_;
    }

    COMMONAPI_EXPORT BrakeStatusStubRemoteEvent* initStubAdapter(const std::shared_ptr< BrakeStatusStubAdapter> &_adapter) {
        CommonAPI::Stub<BrakeStatusStubAdapter, BrakeStatusStubRemoteEvent>::stubAdapter_ = _adapter;
        return &remoteEventHandler_;
    }

    COMMONAPI_EXPORT virtual const bool &getBrakeAttribute() {
        return brakeAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const bool &getBrakeAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getBrakeAttribute();
    }
    COMMONAPI_EXPORT virtual void setBrakeAttribute(bool _value) {
        const bool valueChanged = trySetBrakeAttribute(std::move(_value));
        if (valueChanged) {
            fireBrakeAttributeChanged(brakeAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual void setBrakeAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, bool _value) {
        (void)_client;
        setBrakeAttribute(_value);
    }


protected:
    COMMONAPI_EXPORT virtual bool trySetBrakeAttribute(bool _value) {
        if (!validateBrakeAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<BrakeStatusStubAdapter> stubAdapter = CommonAPI::Stub<BrakeStatusStubAdapter, BrakeStatusStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockBrakeAttribute(true);
            valueChanged = (brakeAttributeValue_ != _value);
            brakeAttributeValue_ = std::move(_value);
            stubAdapter->lockBrakeAttribute(false);
        } else {
            valueChanged = (brakeAttributeValue_ != _value);
            brakeAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateBrakeAttributeRequestedValue(const bool &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual void onRemoteBrakeAttributeChanged() {
        // No operation in default
    }
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual BrakeStatusStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(BrakeStatusStubDefault *_defaultStub)
            : 
              defaultStub_(_defaultStub) {
        }

        COMMONAPI_EXPORT virtual void onRemoteBrakeAttributeChanged() {
            assert(defaultStub_ !=NULL);
            defaultStub_->onRemoteBrakeAttributeChanged();
        }

        COMMONAPI_EXPORT virtual bool onRemoteSetBrakeAttribute(bool _value) {
            assert(defaultStub_ !=NULL);
            return defaultStub_->trySetBrakeAttribute(std::move(_value));
        }

        COMMONAPI_EXPORT virtual bool onRemoteSetBrakeAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, bool _value) {
            (void)_client;
            return onRemoteSetBrakeAttribute(_value);
        }

    private:
        BrakeStatusStubDefault *defaultStub_;
    };
protected:
    BrakeStatusStubDefault::RemoteEventHandler remoteEventHandler_;

private:

    bool brakeAttributeValue_ {};

    CommonAPI::Version interfaceVersion_;
};

} // namespace commonapi
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COMMONAPI_Brake_Status_STUB_DEFAULT
