/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COMMONAPI_Vehicle_Status_PROXY_HPP_
#define V1_COMMONAPI_Vehicle_Status_PROXY_HPP_

#include <v1/commonapi/VehicleStatusProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/AttributeExtension.hpp>
#include <CommonAPI/Factory.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {

template <typename ... _AttributeExtensions>
class VehicleStatusProxy
    : virtual public VehicleStatus,
      virtual public VehicleStatusProxyBase,
      virtual public _AttributeExtensions... {
public:
    VehicleStatusProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~VehicleStatusProxy();

    typedef VehicleStatus InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Returns the wrapper class that provides access to the attribute Speed.
     */
    virtual SpeedAttribute& getSpeedAttribute() {
        return delegate_->getSpeedAttribute();
    }
    /**
     * Returns the wrapper class that provides access to the attribute Battery.
     */
    virtual BatteryAttribute& getBatteryAttribute() {
        return delegate_->getBatteryAttribute();
    }
    /**
     * Returns the wrapper class that provides access to the attribute Brake.
     */
    virtual BrakeAttribute& getBrakeAttribute() {
        return delegate_->getBrakeAttribute();
    }
    /**
     * Returns the wrapper class that provides access to the attribute Temp.
     */
    virtual TempAttribute& getTempAttribute() {
        return delegate_->getTempAttribute();
    }



 private:
    std::shared_ptr< VehicleStatusProxyBase> delegate_;
};

typedef VehicleStatusProxy<> VehicleStatusProxyDefault;

namespace VehicleStatusExtensions {
    template <template <typename > class _ExtensionType>
    class SpeedAttributeExtension {
     public:
        typedef _ExtensionType< VehicleStatusProxyBase::SpeedAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< VehicleStatusProxyBase::SpeedAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        SpeedAttributeExtension(VehicleStatusProxyBase& proxy): attributeExtension_(proxy.getSpeedAttribute()) {
        }
    
        inline extension_type& getSpeedAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

    template <template <typename > class _ExtensionType>
    class BatteryAttributeExtension {
     public:
        typedef _ExtensionType< VehicleStatusProxyBase::BatteryAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< VehicleStatusProxyBase::BatteryAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        BatteryAttributeExtension(VehicleStatusProxyBase& proxy): attributeExtension_(proxy.getBatteryAttribute()) {
        }
    
        inline extension_type& getBatteryAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

    template <template <typename > class _ExtensionType>
    class BrakeAttributeExtension {
     public:
        typedef _ExtensionType< VehicleStatusProxyBase::BrakeAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< VehicleStatusProxyBase::BrakeAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        BrakeAttributeExtension(VehicleStatusProxyBase& proxy): attributeExtension_(proxy.getBrakeAttribute()) {
        }
    
        inline extension_type& getBrakeAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

    template <template <typename > class _ExtensionType>
    class TempAttributeExtension {
     public:
        typedef _ExtensionType< VehicleStatusProxyBase::TempAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< VehicleStatusProxyBase::TempAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        TempAttributeExtension(VehicleStatusProxyBase& proxy): attributeExtension_(proxy.getTempAttribute()) {
        }
    
        inline extension_type& getTempAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

} // namespace VehicleStatusExtensions

//
// VehicleStatusProxy Implementation
//
template <typename ... _AttributeExtensions>
VehicleStatusProxy<_AttributeExtensions...>::VehicleStatusProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< VehicleStatusProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< VehicleStatusProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
VehicleStatusProxy<_AttributeExtensions...>::~VehicleStatusProxy() {
}


template <typename ... _AttributeExtensions>
const CommonAPI::Address &VehicleStatusProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool VehicleStatusProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool VehicleStatusProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& VehicleStatusProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& VehicleStatusProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> VehicleStatusProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace commonapi
} // namespace v1

namespace CommonAPI {
template<template<typename > class _AttributeExtension>
struct DefaultAttributeProxyHelper< ::v1::commonapi::VehicleStatusProxy,
    _AttributeExtension> {
    typedef typename ::v1::commonapi::VehicleStatusProxy<
            ::v1::commonapi::VehicleStatusExtensions::SpeedAttributeExtension<_AttributeExtension>, 
            ::v1::commonapi::VehicleStatusExtensions::BatteryAttributeExtension<_AttributeExtension>, 
            ::v1::commonapi::VehicleStatusExtensions::BrakeAttributeExtension<_AttributeExtension>, 
            ::v1::commonapi::VehicleStatusExtensions::TempAttributeExtension<_AttributeExtension>
    > class_t;
};
}


// Compatibility
namespace v1_0 = v1;

#endif // V1_COMMONAPI_Vehicle_Status_PROXY_HPP_
