/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/commonapi/VehicleStatusSomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createVehicleStatusSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< VehicleStatusSomeIPProxy>(_address, _connection);
}

void initializeVehicleStatusSomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:commonapi.VehicleStatus:v1_0:VehicleStatus",
        0x1235, 0x5679, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
        "commonapi.VehicleStatus:v1_0",
        &createVehicleStatusSomeIPProxy);
}

INITIALIZER(registerVehicleStatusSomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeVehicleStatusSomeIPProxy);
}

VehicleStatusSomeIPProxy::VehicleStatusSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection),
          speed_(*this, CommonAPI::SomeIP::eventgroup_id_t(0x8110), CommonAPI::SomeIP::event_id_t(0x8110), CommonAPI::SomeIP::method_id_t(0xfa0), true, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE, false, CommonAPI::SomeIP::method_id_t(0xfa1), true, static_cast< CommonAPI::SomeIP::IntegerDeployment<int16_t>* >(nullptr)),
          battery_(*this, CommonAPI::SomeIP::eventgroup_id_t(0x811a), CommonAPI::SomeIP::event_id_t(0x811a), CommonAPI::SomeIP::method_id_t(0x1388), true, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE, false, CommonAPI::SomeIP::method_id_t(0x1389), true, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr)),
          brake_(*this, CommonAPI::SomeIP::eventgroup_id_t(0x8124), CommonAPI::SomeIP::event_id_t(0x8124), CommonAPI::SomeIP::method_id_t(0x1770), true, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE, false, CommonAPI::SomeIP::method_id_t(0x1771), true, static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
          temp_(*this, CommonAPI::SomeIP::eventgroup_id_t(0x812e), CommonAPI::SomeIP::event_id_t(0x812e), CommonAPI::SomeIP::method_id_t(0x1b58), true, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE, false, CommonAPI::SomeIP::method_id_t(0x1b59), true, static_cast< CommonAPI::SomeIP::IntegerDeployment<int16_t>* >(nullptr))
{
}

VehicleStatusSomeIPProxy::~VehicleStatusSomeIPProxy() {
    completed_.set_value();
}

VehicleStatusSomeIPProxy::SpeedAttribute& VehicleStatusSomeIPProxy::getSpeedAttribute() {
    return speed_;
}
VehicleStatusSomeIPProxy::BatteryAttribute& VehicleStatusSomeIPProxy::getBatteryAttribute() {
    return battery_;
}
VehicleStatusSomeIPProxy::BrakeAttribute& VehicleStatusSomeIPProxy::getBrakeAttribute() {
    return brake_;
}
VehicleStatusSomeIPProxy::TempAttribute& VehicleStatusSomeIPProxy::getTempAttribute() {
    return temp_;
}


void VehicleStatusSomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 1;
    ownVersionMinor = 0;
}

std::future<void> VehicleStatusSomeIPProxy::getCompletionFuture() {
    return completed_.get_future();
}

} // namespace commonapi
} // namespace v1
