/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/commonapi/BrakeStatusSomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createBrakeStatusSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< BrakeStatusSomeIPProxy>(_address, _connection);
}

void initializeBrakeStatusSomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:commonapi.BrakeStatus:v1_0:BrakeStatus",
        0x1237, 0x567b, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
        "commonapi.BrakeStatus:v1_0",
        &createBrakeStatusSomeIPProxy);
}

INITIALIZER(registerBrakeStatusSomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeBrakeStatusSomeIPProxy);
}

BrakeStatusSomeIPProxy::BrakeStatusSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection),
          brake_(*this, CommonAPI::SomeIP::eventgroup_id_t(0x8124), CommonAPI::SomeIP::event_id_t(0x8124), CommonAPI::SomeIP::method_id_t(0x1770), true, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE, false, CommonAPI::SomeIP::method_id_t(0x1771), true, static_cast< CommonAPI::EmptyDeployment* >(nullptr))
{
}

BrakeStatusSomeIPProxy::~BrakeStatusSomeIPProxy() {
    completed_.set_value();
}

BrakeStatusSomeIPProxy::BrakeAttribute& BrakeStatusSomeIPProxy::getBrakeAttribute() {
    return brake_;
}


void BrakeStatusSomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 1;
    ownVersionMinor = 0;
}

std::future<void> BrakeStatusSomeIPProxy::getCompletionFuture() {
    return completed_.get_future();
}

} // namespace commonapi
} // namespace v1
