/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V1_COMMONAPI_HEAD_UNIT_SOMEIP_STUB_ADAPTER_HPP_
#define V1_COMMONAPI_HEAD_UNIT_SOMEIP_STUB_ADAPTER_HPP_

#include <v1/commonapi/HeadUnitStub.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {

template <typename _Stub = ::v1::commonapi::HeadUnitStub, typename... _Stubs>
class HeadUnitSomeIPStubAdapterInternal
    : public virtual HeadUnitStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< HeadUnitSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> HeadUnitSomeIPStubAdapterHelper;

    ~HeadUnitSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        HeadUnitSomeIPStubAdapterHelper::deinit();
    }

    void fireGearAttributeChanged(const int8_t &_value);
    
    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::commonapi::HeadUnitStub,
        CommonAPI::Version
    > getHeadUnitInterfaceVersionStubDispatcher;

    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::commonapi::HeadUnitStub,
        int8_t,
        CommonAPI::SomeIP::IntegerDeployment<int8_t>
    > getGearAttributeStubDispatcher;
    
    CommonAPI::SomeIP::SetObservableAttributeStubDispatcher<
        ::v1::commonapi::HeadUnitStub,
        int8_t,
        CommonAPI::SomeIP::IntegerDeployment<int8_t>
    > setGearAttributeStubDispatcher;
    
    HeadUnitSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        HeadUnitSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< HeadUnitStub>(_stub)),
        getHeadUnitInterfaceVersionStubDispatcher(&HeadUnitStub::lockInterfaceVersionAttribute, &HeadUnitStub::getInterfaceVersion, false, true),
        getGearAttributeStubDispatcher(
            &::v1::commonapi::HeadUnitStub::lockGearAttribute,
            &::v1::commonapi::HeadUnitStub::getGearAttribute,
            false,
            _stub->hasElement(0)),
        setGearAttributeStubDispatcher(
            &::v1::commonapi::HeadUnitStub::lockGearAttribute,
            &::v1::commonapi::HeadUnitStub::getGearAttribute,
            &HeadUnitStubRemoteEvent::onRemoteSetGearAttribute,
            &HeadUnitStubRemoteEvent::onRemoteGearAttributeChanged,
            &HeadUnitStubAdapter::fireGearAttributeChanged,
            false,
            _stub->hasElement(0))
    {
        HeadUnitSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0xbb8) }, &getGearAttributeStubDispatcher );
        HeadUnitSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0xbb9) }, &setGearAttributeStubDispatcher );
        std::shared_ptr<CommonAPI::SomeIP::ClientId> itsClient = std::make_shared<CommonAPI::SomeIP::ClientId>(0xFFFF, 0xFFFFFFFF, 0xFFFFFFFF);

        // Provided events/fields
        if (_stub->hasElement(0)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x80f2)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x80f2), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE);
            fireGearAttributeChanged(std::dynamic_pointer_cast< ::v1::commonapi::HeadUnitStub>(_stub)->getGearAttribute(itsClient));
        }

    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};

template <typename _Stub, typename... _Stubs>
void HeadUnitSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireGearAttributeChanged(const int8_t &_value) {
    CommonAPI::Deployable< int8_t, CommonAPI::SomeIP::IntegerDeployment<int8_t>> deployedValue(_value, static_cast< CommonAPI::SomeIP::IntegerDeployment<int8_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                int8_t,
                CommonAPI::SomeIP::IntegerDeployment<int8_t>
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0x80f2),
        false,
        deployedValue
    );
}


template <typename _Stub, typename... _Stubs>
void HeadUnitSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {
}

template <typename _Stub, typename... _Stubs>
void HeadUnitSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {
}

template <typename _Stub = ::v1::commonapi::HeadUnitStub, typename... _Stubs>
class HeadUnitSomeIPStubAdapter
    : public HeadUnitSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    HeadUnitSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          HeadUnitSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace commonapi
} // namespace v1

#endif // V1_COMMONAPI_Head_Unit_SOMEIP_STUB_ADAPTER_HPP_
