/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V1_COMMONAPI_TEMP_STATUS_SOMEIP_STUB_ADAPTER_HPP_
#define V1_COMMONAPI_TEMP_STATUS_SOMEIP_STUB_ADAPTER_HPP_

#include <v1/commonapi/TempStatusStub.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {

template <typename _Stub = ::v1::commonapi::TempStatusStub, typename... _Stubs>
class TempStatusSomeIPStubAdapterInternal
    : public virtual TempStatusStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< TempStatusSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> TempStatusSomeIPStubAdapterHelper;

    ~TempStatusSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        TempStatusSomeIPStubAdapterHelper::deinit();
    }

    void fireTempAttributeChanged(const int16_t &_value);
    
    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::commonapi::TempStatusStub,
        CommonAPI::Version
    > getTempStatusInterfaceVersionStubDispatcher;

    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::commonapi::TempStatusStub,
        int16_t,
        CommonAPI::SomeIP::IntegerDeployment<int16_t>
    > getTempAttributeStubDispatcher;
    
    CommonAPI::SomeIP::SetObservableAttributeStubDispatcher<
        ::v1::commonapi::TempStatusStub,
        int16_t,
        CommonAPI::SomeIP::IntegerDeployment<int16_t>
    > setTempAttributeStubDispatcher;
    
    TempStatusSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        TempStatusSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< TempStatusStub>(_stub)),
        getTempStatusInterfaceVersionStubDispatcher(&TempStatusStub::lockInterfaceVersionAttribute, &TempStatusStub::getInterfaceVersion, false, true),
        getTempAttributeStubDispatcher(
            &::v1::commonapi::TempStatusStub::lockTempAttribute,
            &::v1::commonapi::TempStatusStub::getTempAttribute,
            false,
            _stub->hasElement(0)),
        setTempAttributeStubDispatcher(
            &::v1::commonapi::TempStatusStub::lockTempAttribute,
            &::v1::commonapi::TempStatusStub::getTempAttribute,
            &TempStatusStubRemoteEvent::onRemoteSetTempAttribute,
            &TempStatusStubRemoteEvent::onRemoteTempAttributeChanged,
            &TempStatusStubAdapter::fireTempAttributeChanged,
            false,
            _stub->hasElement(0))
    {
        TempStatusSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x1b58) }, &getTempAttributeStubDispatcher );
        TempStatusSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x1b59) }, &setTempAttributeStubDispatcher );
        std::shared_ptr<CommonAPI::SomeIP::ClientId> itsClient = std::make_shared<CommonAPI::SomeIP::ClientId>(0xFFFF, 0xFFFFFFFF, 0xFFFFFFFF);

        // Provided events/fields
        if (_stub->hasElement(0)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x812e)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x812e), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE);
            fireTempAttributeChanged(std::dynamic_pointer_cast< ::v1::commonapi::TempStatusStub>(_stub)->getTempAttribute(itsClient));
        }

    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};

template <typename _Stub, typename... _Stubs>
void TempStatusSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireTempAttributeChanged(const int16_t &_value) {
    CommonAPI::Deployable< int16_t, CommonAPI::SomeIP::IntegerDeployment<int16_t>> deployedValue(_value, static_cast< CommonAPI::SomeIP::IntegerDeployment<int16_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                int16_t,
                CommonAPI::SomeIP::IntegerDeployment<int16_t>
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0x812e),
        false,
        deployedValue
    );
}


template <typename _Stub, typename... _Stubs>
void TempStatusSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {
}

template <typename _Stub, typename... _Stubs>
void TempStatusSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {
}

template <typename _Stub = ::v1::commonapi::TempStatusStub, typename... _Stubs>
class TempStatusSomeIPStubAdapter
    : public TempStatusSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    TempStatusSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          TempStatusSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace commonapi
} // namespace v1

#endif // V1_COMMONAPI_Temp_Status_SOMEIP_STUB_ADAPTER_HPP_
